### ISSUE TITLE
Presentation for Sprint 2

### ISSUE THREAD

**Issue by cblanto7** [MSUTeam1/unbanner#23]
As Dr. Beaty, I want a presentation I might have y'all present on Thursday, September 14.
An upload on Moodle is due by Sunday, September 17, 2017, 11:55 PM

please see: [https://gouda.msudenver.edu/moodle/mod/assign/view.php?id=5575](https://gouda.msudenver.edu/moodle/mod/assign/view.php?id=5575
)
This presentation should contain the following items:

- [x] Choose and implement a continuous integration tool. #18
- [x] Choose and implement build tool. #21 
- [ ] Choose and implement TDD method. #20 
- [ ] Choose a test coverage tool. #22 
- [ ] Decide on the definition of done. #24 
- [x] Choose a templating engine. #25 
- [ ] Live demo (bring up github and slack on a laptop)
- [ ] retrospective (what went well, what went poorly)

Only 1 Team member will turn this in on Moodle

**Comment by toasterbrain** [comment]
After a cursory google search it seems that Scrum is our TDD method and we have decided on Junit as our test coverage tool. We seem to have these mislabeled and as I am 'fixing' it I wanted to document that change.
